# Generated by Django 6.0.3 on 2026-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="raw_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
