# Generated by Django 6.0.3 on 2026-03-19 05:30

import django.db.models.deletion
import myapi.utilities.validators.file_size_validation
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_document_raw_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    myapi.utilities.validators.file_size_validation.validate_file_size
                ],
            ),
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk", models.TextField()),
                ("chunk_index", models.IntegerField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                ("page_number", models.IntegerField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="myapi.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="document_chunk_embedding_hnsw_idx",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
