# Generated by Django 6.0.3 on 2026-03-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_alter_document_doc_name_documentchunk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="document_hnsw_idx",
            old_name="document_chunk_embedding_hnsw_idx",
        ),
    ]
