# Generated by Django 6.0.3 on 2026-03-21 05:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0004_rename_document_chunk_embedding_hnsw_idx_document_hnsw_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, null=True
            ),
        ),
    ]
