# Generated by Django 6.0.3 on 2026-03-21 17:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0005_alter_documentchunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="myapi_docum_search__642bd2_gin"
            ),
        ),
    ]
