# Generated by Django 6.0.3 on 2026-03-28 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0008_chathistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chathistory",
            options={},
        ),
        migrations.AddIndex(
            model_name="chathistory",
            index=models.Index(
                fields=["user", "session_id", "created_at"],
                name="myapi_chath_user_id_0e2c1f_idx",
            ),
        ),
    ]
